### ISSUE TITLE
API details for video feeds

### ISSUE THREAD

**Issue by vdrover** [jasmas/homebridge-platform-blink-security#1]
@jasmas I saw on this thread your comment about looking for API details for video: https://community.blinkforhome.com/t/blink-with-homebridge/1040

Does this project help? https://github.com/MattTW/BlinkMonitorProtocol

Like you, having blink cameras show up as native cameras in Homekit would be ideal, as would triggers based on motion detection.

**Comment by jasmas** [comment]
I think we would need the API to receive the live stream based on what the HAP protocol expects of a video accessory.

**Comment by jasmas** [comment]
We were working on this here: https://github.com/MattTW/BlinkMonitorProtocol/issues/12
