### ISSUE TITLE
Disabling "unauthorized" 3rd Pary Automation Scripts

### ISSUE THREAD

**Issue by Sungamm** [jasmas/homebridge-platform-blink-security#11]
Good Morning,

I received following email from the "The blink team"

**_> Dear Blink Customer, 			  		 		 			 			 				 					 						 						 							 								 									You are receiving  this email because your account has used automation scripts that use an  outdated login method to connect to your Blink account. With  security and customer protection as our top priority, that login method  is being deprecated.  This means that any scripts you are using will no  longer work as of 5/11. 									  									We encourage you to try out IFTTT, our supported 3rd party  integration, for more secure automation functionality. If you have  other feature preferences or requests, you can always email product  feedback to info@blinkforhome.com for consideration. 									  								 							 						 						 					 					 						 						Thank you, 						  						Team Blink_** 

My question to the blink team did not answered. Are you aware of this and do you have any workaround tips?

best regards

**Comment by gdotp01** [comment]
Hi. Ive got the same issue and it's now failing. If you dig into it the community is aware of the issue and have a working solution. What Im uni;lcear of is how this finds its way back to this plugin.

**Comment by lovie** [comment]
Yes - broken for me too.

**Comment by bartdorsey** [comment]
Hi, I'm the developer of https://github.com/bartdorsey/homebridge-blinkcameras. And I've updated my plugin to work correctly with 2fa if you want to give it a shot.  @jasmas can feel free to pull the work I've done on my plugin into this one if he likes.

**Comment by lovie** [comment]
Ok- will try it. Updated the version of node-blink-security to 4.1.0 in package.json and it mostly works.

**Comment by bartdorsey** [comment]
I can see about updating to that, I’ll have to see what all that fixes.

**Comment by bartdorsey** [comment]
It looks like 4.1.0 just adds the ability to record a clip using the API.

**Comment by lovie** [comment]
4.0.0 added 2FA support [here](https://github.com/madshall/node-blink-security/commit/78fc495f482f5c819714a93db9f65a2e7d799e06)

**Comment by bartdorsey** [comment]
Oh sorry, yes, I updated my plugin homebridge-blinkcameras to use this new version. It’ll be up to @jasmas to update this package.

**Comment by gdotp01** [comment]
I's just like to say a big thanks to all those who got this working again. I updated to Homebridge Blinkcameras
homebridge-blinkcameras v1.0.2 did the email shuffle with Blink and its all working again. 

Thanks all !

**Comment by Sungamm** [comment]
I installed the blink plug-in from bartdorsey and it works for me perfect!
