### ISSUE TITLE
Why the author couldn't be bothered with adding instructions?

### ISSUE THREAD

**Issue by ratsoid** [jasmas/homebridge-platform-blink-security#5]
I'd like to know what was the reason why the author didn't bother adding some instructions on how to install this? I'm not even in the mood of explaining my issues because I certainly did something wrong when installing I install this thing... probably I messed something up when installing node-blink-security?
Isn't there like a common sense thing to just write the lines needed to properly install a homebridge plugin? Or is it to much to ask? I honestly don't get it man.

**Comment by marcingminski** [comment]
Hi, I am not an author but have recently installed the plugin and can help you. The installation is very easy and done the same way as any other Homebridge plugin. Providing you have Homebridge installed and configured, you just run:
`npm install -g homebridge-platform-blink-security`
and modify config.json as explained on the home page i.e. add your blink login and password.
Let me know if you need help.

**Comment by ratsoid** [comment]
Thanks man, I got it working.
I think the problem was with the fact that I was stupid enough to leave the damn "//comment" that the author left in the damn "discovery" property and I didn't ran the code through jsonlint to check for errors.

Hey author, how about remove the "// optional: set to false to disable intermittent discovery" from the example, huh?

**Comment by marcingminski** [comment]
Ah fair point, I must have automatically removed the comment without thinking about it.

**Comment by jasmas** [comment]
@ratsoid Instructions for installing homebridge plugins are included with homebridge and the comment you mentioned is self-documenting, is it not?
