### ISSUE TITLE
Blink Cameras Arm/Disarm/Motion

### ISSUE THREAD

**Issue by vkmotwani** [jasmas/homebridge-platform-blink-security#9]
Hello and thanks in advance for any help.  I have 2 Blink Modules and 4 Blink cameras (3 on one module and 1 on the other) that I want to connect to HomeKit via Homebridge on my Raspberry Pi 4.  I installed the bomebridge-blinkcameras plug in and see all the devices in the Accessories as well as in Home on my phone.  However, I'm unable to arm/disarm them.  I have the platform code under platforms in my config file, what else do I need?  Thanks.

**Comment by jasmas** [comment]
Module does not yet support multiple base systems. See #2
